
INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Room Manager','com_accommodation_manager.roommanager','{"special":{"dbtable":"#__accommodation_manager_rooms","key":"id","type":"Roommanager","prefix":"Accommodation_managerTable"}}', '{"formFile":"administrator\/components\/com_accommodation_manager\/models\/forms\/roommanager.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"room_category","targetTable":"#__accommodation_manager_room_categories","targetColumn":"id","displayColumn":"room_category_title"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_accommodation_manager.roommanager')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Room Manager', 
	`table` = '{"special":{"dbtable":"#__accommodation_manager_rooms","key":"id","type":"Room Manager","prefix":"Accommodation_managerTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_accommodation_manager\/models\/forms\/roommanager.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"room_category","targetTable":"#__accommodation_manager_room_categories","targetColumn":"id","displayColumn":"room_category_title"}]}'
WHERE (`type_alias` = 'com_accommodation_manager.roommanager');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Manager Category','com_accommodation_manager.roommanagercategory','{"special":{"dbtable":"#__accommodation_manager_room_categories","key":"id","type":"Roommanagercategory","prefix":"Accommodation_managerTable"}}', '{"formFile":"administrator\/components\/com_accommodation_manager\/models\/forms\/roommanagercategory.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"room_category_parent","targetTable":"#__accommodation_manager_room_categories","targetColumn":"id","displayColumn":"room_category_title"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_accommodation_manager.roommanagercategory')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Manager Category', 
	`table` = '{"special":{"dbtable":"#__accommodation_manager_room_categories","key":"id","type":"Manager Category","prefix":"Accommodation_managerTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_accommodation_manager\/models\/forms\/roommanagercategory.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"room_category_parent","targetTable":"#__accommodation_manager_room_categories","targetColumn":"id","displayColumn":"room_category_title"}]}'
WHERE (`type_alias` = 'com_accommodation_manager.roommanagercategory');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Rate Period','com_accommodation_manager.managerrateperiod','{"special":{"dbtable":"#__accommodation_manager_rate_periods","key":"id","type":"Managerrateperiod","prefix":"Accommodation_managerTable"}}', '{"formFile":"administrator\/components\/com_accommodation_manager\/models\/forms\/managerrateperiod.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_accommodation_manager.managerrateperiod')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Rate Period', 
	`table` = '{"special":{"dbtable":"#__accommodation_manager_rate_periods","key":"id","type":"Rate Period","prefix":"Accommodation_managerTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_accommodation_manager\/models\/forms\/managerrateperiod.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_accommodation_manager.managerrateperiod');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Rate','com_accommodation_manager.managerrate','{"special":{"dbtable":"#__accommodation_manager_rates","key":"id","type":"Managerrate","prefix":"Accommodation_managerTable"}}', '{"formFile":"administrator\/components\/com_accommodation_manager\/models\/forms\/managerrate.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"room_id","targetTable":"#__accommodation_manager_rooms","targetColumn":"id","displayColumn":"id"},{"sourceColumn":"period_id","targetTable":"#__accommodation_manager_rate_periods","targetColumn":"id","displayColumn":"id"},{"sourceColumn":"typology_id","targetTable":"#__accommodation_manager_rate_typologies","targetColumn":"id","displayColumn":"id"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_accommodation_manager.managerrate')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Rate', 
	`table` = '{"special":{"dbtable":"#__accommodation_manager_rates","key":"id","type":"Rate","prefix":"Accommodation_managerTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_accommodation_manager\/models\/forms\/managerrate.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"room_id","targetTable":"#__accommodation_manager_rooms","targetColumn":"id","displayColumn":"id"},{"sourceColumn":"period_id","targetTable":"#__accommodation_manager_rate_periods","targetColumn":"id","displayColumn":"id"},{"sourceColumn":"typology_id","targetTable":"#__accommodation_manager_rate_typologies","targetColumn":"id","displayColumn":"id"}]}'
WHERE (`type_alias` = 'com_accommodation_manager.managerrate');

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
SELECT * FROM ( SELECT 'Rate Typology','com_accommodation_manager.managerratetypology','{"special":{"dbtable":"#__accommodation_manager_rate_typologies","key":"id","type":"Managerratetypology","prefix":"Accommodation_managerTable"}}', '{"formFile":"administrator\/components\/com_accommodation_manager\/models\/forms\/managerratetypology.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}') AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_accommodation_manager.managerratetypology')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Rate Typology', 
	`table` = '{"special":{"dbtable":"#__accommodation_manager_rate_typologies","key":"id","type":"Rate Typology","prefix":"Accommodation_managerTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_accommodation_manager\/models\/forms\/managerratetypology.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"}]}'
WHERE (`type_alias` = 'com_accommodation_manager.managerratetypology');
